name: Release
on:
  push:
    branches:
      - master
      - '[0-9]+.x'
      - '[0-9]+.[0-9]+.x'
jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Release
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: Brightspace/third-party-actions@actions/checkout
        with:
          persist-credentials: false
      - name: Setup Node
        uses: Brightspace/third-party-actions@actions/setup-node
      - name: Install dependencies
        run: npm ci
      - name: Unit Tests (Headless)
        run: npm run test:headless
      - name: Incremental Release
        uses: BrightspaceUI/actions/incremental-release@master
        with:
          DEFAULT_INCREMENT: minor
          GITHUB_TOKEN: ${{ secrets.D2L_GITHUB_TOKEN }}
